
package com.EmployeeService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "employeeService", targetNamespace = "http://com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @return
     *     returns com.EmployeeService.GetEmployeeListResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeList", targetNamespace = "http://com/", className = "com.EmployeeService.GetEmployeeList")
    @ResponseWrapper(localName = "getEmployeeListResponse", targetNamespace = "http://com/", className = "com.EmployeeService.GetEmployeeListResponse")
    public com.EmployeeService.GetEmployeeListResponse.Return getEmployeeList();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.EmployeeService.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://com/", className = "com.EmployeeService.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://com/", className = "com.EmployeeService.GetEmployeeByIdResponse")
    public Employee getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeId arg0);

    /**
     * 
     * @return
     *     returns com.EmployeeService.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://com/", className = "com.EmployeeService.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://com/", className = "com.EmployeeService.GetEmployeeResponse")
    public Employee getEmployee();

}
