
package com.EmployeeService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EmployeeServiceService", targetNamespace = "http://com/", wsdlLocation = "http://localhost:8080/SampleOne-0.0.1-SNAPSHOT/emp?wsdl")
public class EmployeeServiceService
    extends Service
{

    private final static URL EMPLOYEESERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.EmployeeService.EmployeeServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.EmployeeService.EmployeeServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/SampleOne-0.0.1-SNAPSHOT/emp?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/SampleOne-0.0.1-SNAPSHOT/emp?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EMPLOYEESERVICESERVICE_WSDL_LOCATION = url;
    }

    public EmployeeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeServiceService() {
        super(EMPLOYEESERVICESERVICE_WSDL_LOCATION, new QName("http://com/", "EmployeeServiceService"));
    }

    /**
     * 
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "employeeServicePort")
    public EmployeeService getEmployeeServicePort() {
        return super.getPort(new QName("http://com/", "employeeServicePort"), EmployeeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "employeeServicePort")
    public EmployeeService getEmployeeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/", "employeeServicePort"), EmployeeService.class, features);
    }

}
